### ISSUE TITLE
getting a lot of erros and I am not sure what to do. 

### ISSUE THREAD

**Issue by TreeFiddy112** [shantnu/RedditBot#10]
Traceback (most recent call last):
  File "C:/Users/B/PycharmProjects/RedditBot/RedditBot1.py", line 8, in <module>
    for submission in subreddit.hot(limit=5):
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\praw\models\listing\generator.py", line 61, in __next__
    self._next_batch()
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\praw\models\listing\generator.py", line 71, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\praw\reddit.py", line 454, in get
    data = self.request("GET", path, params=params)
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\praw\reddit.py", line 626, in request
    return self._core.request(
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\sessions.py", line 183, in request
    return self._request_with_retries(
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\sessions.py", line 115, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\sessions.py", line 98, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\rate_limit.py", line 35, in call
    kwargs['headers'] = set_header_callback()
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\sessions.py", line 145, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\auth.py", line 327, in refresh
    self._request_token(grant_type='password', username=self._username,
  File "C:\Users\B\PycharmProjects\RedditBot\venv\lib\site-packages\prawcore\auth.py", line 141, in _request_token
    raise OAuthException(response, payload['error'],
prawcore.exceptions.OAuthException: invalid_grant error processing request

Process finished with exit code 1

**Comment by hfrance** [comment]
First use linux and execute python3 yourfile.py
