### ISSUE TITLE
error in part1 bot_read.py

### ISSUE THREAD

**Issue by WiggyWire** [shantnu/RedditBot#8]
I tried the code and I get the following error. 
`dan@wiggy:~/RedditBot$ python3 bot_read.py
Traceback (most recent call last):
  File "bot_read.py", line 8, in <module>
    for submission in subreddit.hot(limit=5):
  File "/home/dan/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/home/dan/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/dan/.local/lib/python3.5/site-packages/praw/reddit.py", line 391, in get
    data = self.request('GET', path, params=params)
  File "/home/dan/.local/lib/python3.5/site-packages/praw/reddit.py", line 506, in request
    params=params)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 185, in request
    params=params, url=url)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 116, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 101, in _make_request
    params=params)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/rate_limit.py", line 35, in call
    kwargs['headers'] = set_header_callback()
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 145, in _set_header_callback
    self._authorizer.refresh()
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/home/dan/.local/lib/python3.5/site-packages/prawcore/auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
`

**Comment by terumiisobe** [comment]
This is happening because you have to user your personal Reddit account information as parameter in the reddit instance init. I fixed it in the PR. https://github.com/shantnu/RedditBot/pull/9
